### ISSUE TITLE
Add description of RabbitMq events

### ISSUE THREAD

**Issue by starkmsu** [OpenMAVN/Welcome#27]
Convert this document:
[EMAAR-EventsMap-190520-0941.pdf](https://github.com/OpenMAVN/Welcome/files/4649541/EMAAR-EventsMap-190520-0941.pdf)
into Events.md file

**Comment by lAnubisl** [comment]
https://github.com/OpenMAVN/Welcome/pull/28

**Comment by starkmsu** [comment]
@lAnubisl , please update links in events-map.md from bitbucket links to corresponding gihub repos un OpenMAVN organization

**Comment by lAnubisl** [comment]
https://github.com/OpenMAVN/Welcome/pull/29

**Comment by lAnubisl** [comment]
@starkmsu If you think this is completed - please close this ticket

**Comment by starkmsu** [comment]
Implemented in linked PR
